"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
import os

# ===== 终极兼容配置 =====
# 1. 【核心】智能判断环境：优先读取环境变量，如果未设置则默认为开发模式
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'  # 默认True
# 2. 【核心】密钥：从环境变量读取，本地开发使用一个固定的弱密钥（仅用于开发）
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-g_v+r&q9i(w59(fp@1p*^no*1b5ycu!u21v=z_rntyky(&i03j')

# 3. 主机与来源配置（自动适应环境）
if DEBUG:
    # *** 本地开发环境 ***
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
    CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://localhost:8000']
else:
    # *** 生产环境 (Koyeb) ***

    # 获取Koyeb应用的全域名
    KOYEB_APP_DOMAIN = os.environ.get('KOYEB_APP_FQDN', 'your-app-name.koyeb.app')
    ALLOWED_HOSTS = [KOYEB_APP_DOMAIN, '.koyeb.app']

    # 【核心修复】Cookie 和安全设置
    # 1. 强制使用HTTPS（如果Koyeb已为你配置了SSL证书，则启用）
    # SECURE_SSL_REDIRECT = True  # 先注释掉，确保能访问

    # 2. 告诉Django我们运行在一个反向代理（如Koyeb的负载均衡器）后面，它能处理好HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # 3. 【关键】Cookie 设置 - 调整为开发兼容模式，确保登录状态持久
    SESSION_COOKIE_SECURE = True  # 设为 False，允许HTTP连接传输会话Cookie（初期调试）
    CSRF_COOKIE_SECURE = True  # 设为 False，允许HTTP连接传输CSRF Cookie
    SESSION_COOKIE_DOMAIN = None  # 设为 None，让Cookie在所有子域下有效
    # 在生产环境配置块（else: 下）中添加

    SESSION_COOKIE_SAMESITE = 'None'


    # 4. 可选：延长会话过期时间（默认为2周）
    SESSION_COOKIE_AGE = 1209600  # 单位是秒（2周）
# ===== 配置结束 =====

CSRF_COOKIE_DOMAIN = '.koyeb.app'
SESSION_COOKIE_DOMAIN = '.koyeb.app'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 第三方应用
    'widget_tweaks',  # 添加这一行
    # 你的应用
    'accounts',
    'posts',
    'interactions',
]

AUTH_USER_MODEL = 'accounts.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# 静态文件配置（开发环境）
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 文件上传设置
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644

# https://docs.djangoproject.com/en/6.0/howto/static-files/
